# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/solveit-modal',
                'doc_host': 'https://ForBo7.github.io',
                'git_url': 'https://github.com/ForBo7/solveit-modal',
                'lib_path': 'solveit_modal'},
  'syms': {'solveit_modal.core': {'solveit_modal.core.foo': ('core.html#foo', 'solveit_modal/core.py')}}}
