# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/solveit-modal',
                'doc_host': 'https://ForBo7.github.io',
                'git_url': 'https://github.com/ForBo7/solveit-modal',
                'lib_path': 'solveit_modal'},
  'syms': { 'solveit_modal.core': {'solveit_modal.core.foo': ('core.html#foo', 'solveit_modal/core.py')},
            'solveit_modal.modal': { 'solveit_modal.modal._ssh': ('modal.html#_ssh', 'solveit_modal/modal.py'),
                                     'solveit_modal.modal.get_pubkey': ('modal.html#get_pubkey', 'solveit_modal/modal.py'),
                                     'solveit_modal.modal.get_tunnel': ('modal.html#get_tunnel', 'solveit_modal/modal.py'),
                                     'solveit_modal.modal.inject_pubkey': ('modal.html#inject_pubkey', 'solveit_modal/modal.py'),
                                     'solveit_modal.modal.mk_img': ('modal.html#mk_img', 'solveit_modal/modal.py'),
                                     'solveit_modal.modal.mk_sandbox': ('modal.html#mk_sandbox', 'solveit_modal/modal.py'),
                                     'solveit_modal.modal.start_ssh': ('modal.html#start_ssh', 'solveit_modal/modal.py'),
                                     'solveit_modal.modal.verify_connection': ('modal.html#verify_connection', 'solveit_modal/modal.py')}}}
