"""Fill in a module description here

Docs: https://ForBo7.github.io/solveit-modalcore.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['foo']

# %% ../nbs/00_core.ipynb #4c01fb59
def foo(): pass
