"""Add/remove a GPU to/from your SolveIt instance in one function.

Docs: https://ForBo7.github.io/solveit-modalcore.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['log', 'provision_sandbox', 'setup_ssh', 'link_remote_kernel', 'gpu_on', 'gpu_off', 'connect_existing_kernel', 'gip',
           'ipf_exec', 'ipf_shutdown', 'ipf_startup', 'local', 'register_remote_kernel', 'remote', 'set_ssh_config',
           'set_sticky', 'start_remote', 'stop_remote', 'unset_sticky']

# %% ../nbs/00_core.ipynb #23c76ec0
from .modal import *
from .ipyfernel import *

# %% ../nbs/00_core.ipynb #3f7d798d
from ipyfernel.core import *

# %% ../nbs/00_core.ipynb #3330ffa2
_all_ = ['connect_existing_kernel', 'gip', 'ipf_exec', 'ipf_shutdown', 'ipf_startup',
         'local', 'register_remote_kernel', 'remote', 'set_ssh_config',
         'set_sticky', 'start_remote', 'stop_remote', 'unset_sticky']

# %% ../nbs/00_core.ipynb #8f64a7c2
def provision_sandbox(
    gpu:str,        # GPU type string, e.g. 'T4', 'A100'
    timeout:int     # Max sandbox lifetime in seconds
) -> tuple:  # (sandbox, host, port)
    "Create Modal app, image, sandbox, and expose TCP tunnel."
    app = mk_app()
    img = mk_img()
    sb = mk_sandbox(app, img, gpu=gpu, timeout=timeout)
    host, port = get_tunnel(sb)
    return sb, host, port

# %% ../nbs/00_core.ipynb #a2ad70d1
import modal

# %% ../nbs/00_core.ipynb #f77b6d0a
def setup_ssh(
    sb  :modal.sandbox.Sandbox,    # Modal Sandbox object
    host:str,                      # Tunnel hostname
    port:int                       # Tunnel port
) -> object:  # Paramiko SSH connection
    "Inject public key, start SSH service, and verify connectivity."
    inject_pubkey(sb, get_pubkey())
    start_ssh(sb)
    ssh = mk_ssh(host, port)
    verify_ssh(ssh)
    return ssh

# %% ../nbs/00_core.ipynb #92f8c6c7
import logging

# %% ../nbs/00_core.ipynb #f7d90970
logging.basicConfig(level=logging.INFO, format='%(message)s - %(levelname)s | %(asctime)s')
log = logging.getLogger(__name__)

# %% ../nbs/00_core.ipynb #c756caba
def link_remote_kernel(
    ssh   :object,     # Paramiko SSH connection
    host  :str,        # Tunnel hostname
    port  :int,        # Tunnel port
    sticky:bool=False  # Set `True` to execute code remotely by default
):
    "Launch remote IPython kernel on sandbox and connect ipyfernel to it."
    start_remote_kernel(ssh)
    p = get_remote_python(ssh)
    register_remote_kernel(remote_python=p)
    connect_existing_kernel(f'{host}:{port}')
    log.info('✔ connected to remote kernel')
    if sticky: 
        set_sticky()
        log.warning('! code will run remotely by default; run `%local unset_sticky` to run code locally')

# %% ../nbs/00_core.ipynb #f2fd6ed6
def gpu_on(
      gpu='T4',    # GPU type string
      timeout=1800 # Max sandbox lifetime in seconds
) -> tuple:        # (sandbox, ssh)
    "Provision a GPU sandbox, wire up SSH, and hijack cells onto a remote kernel."
    sb, host, port = provision_sandbox(gpu, timeout)
    ssh = setup_ssh(sb, host, port)
    link_remote_kernel(ssh, host, port)
    return sb, ssh

# %% ../nbs/00_core.ipynb #7d2d9bae
def gpu_off(
      sb  # sandbox object from gpu_on
):
    "Restore local kernel, disconnect remote, and teardown sandbox. Must be called from a %%local cell."
    unset_sticky()
    stop_remote()
    log.info('✔ unlinked from remote kernel')
    sb.terminate()
    log.info('✔ terminated sandbox')
