"""Connecting a solveit kernel to a Modal sandbox

Docs: https://ForBo7.github.io/solveit-modalipyfernel.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_ipyfernel.ipynb.

# %% auto #0
__all__ = ['start_remote_kernel', 'get_remote_python']

# %% ../nbs/02_ipyfernel.ipynb #c0e9b2f6
from time import sleep

# %% ../nbs/02_ipyfernel.ipynb #24680f70
def start_remote_kernel(ssh,                            # SSH caller from mk_ssh
    kernel_path:str='/root/.local/share/jupyter/runtime/kernel-ipyf.json',  # kernel JSON path
    ) -> None:
    "Start remote kernel and wait until ready."
    ssh('mkdir', '-p', '/root/.local/share/jupyter/runtime')
    ssh(f'nohup python3 -m ipykernel_launcher -f {kernel_path} >/tmp/kernel.log 2>&1 &')
    for i in range(10):
        if 'ok' in ssh(f'test -f {kernel_path} && echo ok || echo no'): break
        sleep(0.2)
    log = ssh('cat /tmp/kernel.log')
    assert 'To connect another client' in log, f'kernel failed to start:\n{log}'
    print(f'✔ remote kernel ready: {kernel_path}')

# %% ../nbs/02_ipyfernel.ipynb #1f53ae0f
def get_remote_python(ssh,                       # SSH caller from mk_ssh
    ) -> str:                                    # path to remote python
    "Return the path of Python on the remote machine."
    return ssh('which python3')

# %% ../nbs/02_ipyfernel.ipynb #6b35bcb8
from ipyfernel.core import *
