"""Connecting a solveit kernel to a Modal sandbox

Docs: https://ForBo7.github.io/solveit-modalkernel.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_kernel.ipynb.

# %% auto #0
__all__ = ['log', 'start_remote_kernel', 'get_remote_python', 'gip', 'register_remote_kernel', 'set_ssh_config', 'ipf_startup',
           'ipf_exec', 'ipf_shutdown', 'connect_existing_kernel', 'start_remote', 'stop_remote', 'remote', 'local',
           'set_sticky', 'unset_sticky']

# %% ../nbs/02_kernel.ipynb #0756ee20
import logging

# %% ../nbs/02_kernel.ipynb #9b0da6bc
logging.basicConfig(level=logging.INFO, format='%(levelname)s - %(message)s | %(asctime)s')
log = logging.getLogger(__name__)

# %% ../nbs/02_kernel.ipynb #c0e9b2f6
from time import sleep

# %% ../nbs/02_kernel.ipynb #f21e4184
from typing import Callable

# %% ../nbs/02_kernel.ipynb #24680f70
def start_remote_kernel(
    ssh:Callable,                                                           # SSH caller from mk_ssh
    kernel_path:str='/root/.local/share/jupyter/runtime/kernel-ipyf.json',  # kernel JSON path
):
    "Start remote kernel and wait until ready."
    log.info('∞ starting kernel')
    ssh('mkdir', '-p', '/root/.local/share/jupyter/runtime')
    ssh(f'nohup python3 -m ipykernel_launcher -f {kernel_path} >/tmp/kernel.log 2>&1 &')
    for i in range(10):
        if 'ok' in ssh(f'test -f {kernel_path} && echo ok || echo no'): break
        sleep(0.2)
    klog = ssh('cat /tmp/kernel.log')
    assert 'To connect another client' in klog, f'kernel failed to start:\n{klog}'
    log.info(f'✔ remote kernel ready: {kernel_path}')

# %% ../nbs/02_kernel.ipynb #1f53ae0f
def get_remote_python(
    ssh:Callable,   # SSH caller from mk_ssh
) -> str:  # path to remote python
    "Return the path of Python on the remote machine."
    return ssh('which python3')

# %% ../nbs/02_kernel.ipynb #6b35bcb8
from ipyfernel.core import *

# %% ../nbs/02_kernel.ipynb #f5508604
_all_ = ['gip','register_remote_kernel','set_ssh_config','ipf_startup','ipf_exec','ipf_shutdown','connect_existing_kernel','start_remote','stop_remote','remote','local','set_sticky','unset_sticky']
