"""Abstractions for creating a Modal Sandbox"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_modal.ipynb.

# %% auto #0
__all__ = ['mk_app', 'mk_img', 'get_apts', 'get_pips', 'get_secrets', 'mk_sandbox', 'get_tunnel', 'get_pubkey', 'inject_pubkey',
           'start_ssh', 'mk_ssh', 'verify_ssh']

# %% ../nbs/01_modal.ipynb #03380e24
import modal

# %% ../nbs/01_modal.ipynb #978005b2
def mk_app(name): return modal.App.lookup(name, create_if_missing=True)

# %% ../nbs/01_modal.ipynb #146ee39d
_default_condas = ['ipykernel', 'fastai', 'cuda-toolkit',]

# %% ../nbs/01_modal.ipynb #433a2601
_default_pips = [
    'ipykernel', 'fastai',
    'transformers', 'diffusers', 'accelerate', 'datasets',
    'huggingface_hub', 'peft', 'bitsandbytes', 'safetensors', 'einops',
    'xformers', 'ninja', 'sentence-transformers', 'wandb', 'gradio',
    'python-fasthtml', 'plotly', 'fsspec', 's3fs', 'gcsfs', 'librosa',
    'imageio', 'imageio-ffmpeg', 'ipywidgets',
]

# %% ../nbs/01_modal.ipynb #90830daf
def mk_img(
    condas=None,  # conda packages (defaults to _default_condas)
    pips=None,    # pip packages (defaults to _default_pips)
):
    if condas is None: condas = _default_condas
    if pips is None: pips = _default_pips
    # return (modal.Image.micromamba()
        # .apt_install('openssh-server')
        # .micromamba_install(condas)
        # .pip_install(pips)
    # )
    return modal.Image.debian_slim().apt_install('openssh-server').pip_install(pips)


# %% ../nbs/01_modal.ipynb #29fc1c0c
def get_apts() -> list[str]:  # installed system package names
    return run('dpkg-query -W -f=\'${Package}\\n\'').splitlines()

# %% ../nbs/01_modal.ipynb #deefc0f2
def get_pips() -> list[str]:  # installed python packages (name==version)
    return [l for l in run('pip freeze').splitlines() if not l.startswith(('-e', '@'))]

# %% ../nbs/01_modal.ipynb #f7772c3a
import json

# %% ../nbs/01_modal.ipynb #4058df3e
def get_secrets() -> dict:  # secrets from solveit_settings.json
    with open('/app/data/solveit_settings.json') as f: return json.load(f)['secrets']

# %% ../nbs/01_modal.ipynb #2c02f113
def mk_sandbox(
    app,            # modal.App to register the Sandbox with
    img,            # modal.Image for the Sandbox environment
    timeout=600,    # auto-terminate after this many seconds
    gpu=None,       # GPU type string (e.g. "T4", "A100") or None for no GPU
    secrets=None,   # dict of secrets (defaults to local solveit secrets)
):
    if secrets is None: secrets = get_secrets()
    return modal.Sandbox.create('sleep', 'infinity',
        app=app, image=img, timeout=timeout,
        unencrypted_ports=[22], gpu=gpu,
        secrets=[modal.Secret.from_dict(secrets)])


# %% ../nbs/01_modal.ipynb #02ca8fce
def get_tunnel(sb):
    t = sb.tunnels()[22]
    return t.unencrypted_host, t.unencrypted_port

# %% ../nbs/01_modal.ipynb #db3e20e6
import os

# %% ../nbs/01_modal.ipynb #76c2029b
def get_pubkey(): return os.environ['SSH_PUBKEY']

# %% ../nbs/01_modal.ipynb #22acba37
def inject_pubkey(sb, pubkey):
    sb.exec('mkdir', '-p', '/root/.ssh')
    sb.exec('bash', '-c', f'echo {pubkey} > /root/.ssh/authorized_keys')

# %% ../nbs/01_modal.ipynb #7c9fbd91
from time import sleep

# %% ../nbs/01_modal.ipynb #a2b3362d
def start_ssh(sb):
    sb.exec('service', 'ssh', 'start')
    for i in range(20):
        proc = sb.exec('service', 'ssh', 'status')
        if 'fail' in proc.stdout.read(): sleep(0.3)
        elif 'run' in proc.stdout.read(): 
            print('✔ started ssh service')
            return
    print('✖ failed to start ssh service')

# %% ../nbs/01_modal.ipynb #1d3817c4
from fastcore.all import *

# %% ../nbs/01_modal.ipynb #310fd93d
def mk_ssh(host, port):
    return lambda *cmd: run('ssh', '-p', str(port),
        '-o', 'StrictHostKeyChecking=no',
        '-o', 'UserKnownHostsFile=~/.ssh/known_hosts',
        '-o', 'ConnectTimeout=10',
        f'root@{host}', *cmd)

# %% ../nbs/01_modal.ipynb #65fc2209
def verify_ssh(ssh):
    "Verify SSH connection to Sandbox and print system info."
    h, u, w = ssh('hostname; uname -srmo; whoami').splitlines()[:3]
    sys_name, ver, arch, os_name = u.split()
    print(f'系统：  {sys_name}')
    print(f'主机名：{h}')
    print(f'用户：  {w}')
    print(f'内核：  {ver}')
    print(f'架构：  {arch}')
    print(f'系统类型：{os_name}')
