"""Abstractions for creating a Modal Sandbox"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_modal.ipynb.

# %% auto #0
__all__ = ['app', 'img', 'sb', 'host', 'port', 'ssh', 'mk_img', 'mk_sandbox', 'get_tunnel', 'get_pubkey', 'inject_pubkey',
           'start_ssh', 'verify_connection']

# %% ../nbs/01_modal.ipynb #03380e24
import modal

# %% ../nbs/01_modal.ipynb #baf23d56
app = modal.App.lookup('solveit-sandbox', create_if_missing=True)

# %% ../nbs/01_modal.ipynb #146ee39d
def mk_img(
    apts,   # system packages to apt-install (list or str)
    pips,   # python packages to pip-install (list or str)
): return modal.Image.debian_slim().apt_install(apts).pip_install(pips)

# %% ../nbs/01_modal.ipynb #e2be7556
img = mk_img('openssh-server', 'ipykernel')

# %% ../nbs/01_modal.ipynb #2c02f113
def mk_sandbox(
    app,        # modal.App to register the Sandbox with
    img,        # modal.Image for the Sandbox environment
    timeout=600, # auto-terminate after this many seconds
):
    return modal.Sandbox.create('sleep', 'infinity', app=app, image=img, timeout=timeout, unencrypted_ports=[22])

# %% ../nbs/01_modal.ipynb #18dab12f
sb = mk_sandbox(app, img)

# %% ../nbs/01_modal.ipynb #02ca8fce
def get_tunnel(sb):
    t = sb.tunnels()[22]
    return t.unencrypted_host, t.unencrypted_port

# %% ../nbs/01_modal.ipynb #cf40aa4b
host, port = get_tunnel(sb)

# %% ../nbs/01_modal.ipynb #db3e20e6
import os

# %% ../nbs/01_modal.ipynb #76c2029b
def get_pubkey(): return os.environ['SSH_PUBKEY']

# %% ../nbs/01_modal.ipynb #22acba37
def inject_pubkey(sb, pubkey):
    sb.exec('mkdir', '-p', '/root/.ssh')
    sb.exec('bash', '-c', f'echo {pubkey} > /root/.ssh/authorized_keys')

# %% ../nbs/01_modal.ipynb #f2e1b8f9
inject_pubkey(sb, get_pubkey())

# %% ../nbs/01_modal.ipynb #7c9fbd91
from time import sleep

# %% ../nbs/01_modal.ipynb #a2b3362d
def start_ssh(sb):
    sb.exec('service', 'ssh', 'start')
    for i in range(20):
        proc = sb.exec('service', 'ssh', 'status')
        if 'fail' in proc.stdout.read(): sleep(0.3)
        elif 'run' in proc.stdout.read(): 
            print('✔ started ssh service')
            return
    print('✖ failed to start ssh service')

# %% ../nbs/01_modal.ipynb #b3ef9624
start_ssh(sb)

# %% ../nbs/01_modal.ipynb #1d3817c4
from fastcore.all import *

# %% ../nbs/01_modal.ipynb #310fd93d
def _ssh(host, port):
    return lambda *cmd: run('ssh', '-p', str(port),
        '-o', 'StrictHostKeyChecking=no',
        '-o', 'UserKnownHostsFile=/dev/null',
        '-o', 'ConnectTimeout=10',
        f'root@{host}', *cmd)

# %% ../nbs/01_modal.ipynb #6d89793f
ssh = _ssh(host,port)

# %% ../nbs/01_modal.ipynb #65fc2209
def verify_connection(ssh):
    "Verify SSH connection to Sandbox and print system info."
    h, u, w = ssh('hostname; uname -srmo; whoami').splitlines()[:3]
    sys_name, ver, arch, os_name = u.split()
    print(f'系统：  {sys_name}')
    print(f'主机名：{h}')
    print(f'用户：  {w}')
    print(f'内核：  {ver}')
    print(f'架构：  {arch}')
    print(f'系统类型：{os_name}')

