"""Abstractions for creating a Modal Sandbox

Docs: https://ForBo7.github.io/solveit-modalmodal.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_modal.ipynb.

# %% auto #0
__all__ = ['mk_app', 'mk_img', 'get_apts', 'get_pips', 'get_secrets', 'mk_sandbox', 'get_tunnel', 'get_pubkey', 'inject_pubkey',
           'start_ssh', 'mk_ssh', 'verify_ssh']

# %% ../nbs/01_modal.ipynb #03380e24
import modal

# %% ../nbs/01_modal.ipynb #978005b2
def mk_app(name:str='solveit-sandbox'        # App name to look up or create
           ) -> modal.App:
    "Look up a Modal App by name, creating it if missing."
    return modal.App.lookup(name, create_if_missing=True)

# %% ../nbs/01_modal.ipynb #146ee39d
_default_condas = ['ipykernel', 'fastai', 'cuda-toolkit',]

# %% ../nbs/01_modal.ipynb #433a2601
_default_pips = [
    'ipykernel',
    'fastai', 'transformers', 'diffusers', 'accelerate', 'datasets',
    'huggingface_hub', 'peft', 'safetensors', 'sentence-transformers',
    'xformers', 'bitsandbytes', 'ninja', 'einops',
    'wandb',
    'gradio', 'python-fasthtml', 'plotly', 'ipywidgets',
    'fsspec', 's3fs', 'gcsfs',
    'librosa', 'imageio', 'imageio-ffmpeg',
]

# %% ../nbs/01_modal.ipynb #90830daf
def mk_img(
    pips  :list|None=None,  # pip packages (defaults to _default_pips)
) -> modal.Image:
    "Create a Modal Image with system + Python packages."
    if pips   is None: pips   = _default_pips
    return modal.Image.debian_slim().apt_install('openssh-server').pip_install(pips)

# %% ../nbs/01_modal.ipynb #29fc1c0c
def get_apts() -> list[str]:
    "List installed system package names."
    return run('dpkg-query -W -f=\'${Package}\\n\'').splitlines()

# %% ../nbs/01_modal.ipynb #deefc0f2
def get_pips() -> list[str]:
    "List installed Python packages (name==version)."
    return [l for l in run('pip freeze').splitlines() if not l.startswith(('-e', '@'))]

# %% ../nbs/01_modal.ipynb #f7772c3a
import json

# %% ../nbs/01_modal.ipynb #4058df3e
def get_secrets() -> dict[str,str]:
    "Secrets from solveit_settings.json."
    with open('/app/data/solveit_settings.json') as f: return json.load(f)['secrets']

# %% ../nbs/01_modal.ipynb #2c02f113
def mk_sandbox(
    app    :modal.App,              # Modal App to register the Sandbox with
    img    :modal.Image,            # Image for the Sandbox environment
    timeout:int        =600,        # auto-terminate after this many seconds
    gpu    :str|None    =None,      # GPU type (e.g. "T4", "A100") or None
    secrets:dict|None   =None,      # secrets dict (defaults to local solveit)
) -> modal.Sandbox:
    "Create a Modal Sandbox with optional GPU and SSH."
    if secrets is None: secrets = get_secrets()
    print(f'⌛ creating sandbox…')
    sb = modal.Sandbox.create('sleep', 'infinity',
        app=app, image=img, timeout=timeout,
        unencrypted_ports=[22], gpu=gpu,
        secrets=[modal.Secret.from_dict(secrets)])
    print('✔ sandbox ready')
    return sb

# %% ../nbs/01_modal.ipynb #02ca8fce
def get_tunnel(sb: modal.Sandbox  # Sandbox with an exposed TCP tunnel
               ) -> tuple[str,int]:
    "Get unencrypted host and port for a Sandbox's TCP tunnel."
    t = sb.tunnels()[22]
    host, port = t.unencrypted_host, t.unencrypted_port
    print(f'✔ tunnel: {host}:{port}')
    return host, port

# %% ../nbs/01_modal.ipynb #db3e20e6
import os

# %% ../nbs/01_modal.ipynb #76c2029b
def get_pubkey() -> str:
    "SSH public key from environment."
    return os.environ['SSH_PUBKEY']

# %% ../nbs/01_modal.ipynb #22acba37
def inject_pubkey(sb    :modal.Sandbox,  # Sandbox to inject the key into
                  pubkey:str             # SSH public key string
                  ):
    "Inject an SSH public key into the Sandbox's authorized_keys."
    sb.exec('mkdir', '-p', '/root/.ssh')
    sb.exec('bash', '-c', f'echo {pubkey} > /root/.ssh/authorized_keys')
    print('✔ public key injected')

# %% ../nbs/01_modal.ipynb #7c9fbd91
from time import sleep

# %% ../nbs/01_modal.ipynb #a2b3362d
def start_ssh(sb: modal.Sandbox  # Sandbox with SSH server installed
              ):
    "Start SSH service in the Sandbox, waiting up to ~6 seconds for it to come online."
    sb.exec('service', 'ssh', 'start')
    for _ in range(20):
        proc = sb.exec('service', 'ssh', 'status')
        if 'fail' in proc.stdout.read(): sleep(0.3)
        elif 'run' in proc.stdout.read():
            print('✔ started ssh service')
            return
    print('✖ failed to start ssh service')

# %% ../nbs/01_modal.ipynb #1d3817c4
from fastcore.all import *

# %% ../nbs/01_modal.ipynb #310fd93d
def mk_ssh(host: str,  # Tunnel host
           port: int,  # Tunnel port
           ) -> object:
    "Return an SSH function for the given Modal tunnel."
    return lambda *cmd: run('ssh', '-p', str(port),
        '-o', 'StrictHostKeyChecking=no',
        '-o', 'UserKnownHostsFile=~/.ssh/known_hosts',
        '-o', 'ConnectTimeout=10',
        f'root@{host}', *cmd)

# %% ../nbs/01_modal.ipynb #65fc2209
def verify_ssh(ssh: object  # SSH function returned by mk_ssh
               ):
    "Verify SSH connection to Sandbox and print system info."
    h, u, w = ssh('hostname; uname -srmo; whoami').splitlines()[:3]
    sys_name, ver, arch, os_name = u.split()
    gpu = ssh('nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null || echo "no GPU"').strip()
    print(f'System: {sys_name}')
    print(f'Hostname: {h}')
    print(f'User: {w}')
    print(f'Kernel: {ver}')
    print(f'Architecture: {arch}')
    print(f'OS Type: {os_name}')
    print(f'GPU: {gpu}')
