"""Abstractions for creating a Modal Sandbox, and interacting with it via SSH.

Docs: https://ForBo7.github.io/solveit-modalsandbox.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_sandbox.ipynb.

# %% auto #0
__all__ = ['log', 'mk_app', 'mk_img', 'mk_vol', 'mk_sandbox', 'get_tunnel', 'get_pubkey', 'inject_pubkey', 'start_ssh', 'mk_ssh',
           'verify_ssh', 'get_apts', 'get_pips', 'in_modal', 'in_solveit']

# %% ../nbs/01_sandbox.ipynb #03380e24
import modal

# %% ../nbs/01_sandbox.ipynb #978005b2
def mk_app(
       name:str  # App name to look up or create 
) -> modal.App:
    "Look up a Modal App by name, creating it if missing."
    return modal.App.lookup(name, create_if_missing=True)

# %% ../nbs/01_sandbox.ipynb #90830daf
def mk_img(
    pips:list, # pip packages to have installed
    apts:list  # apt packages to have installed
) -> modal.Image:
    "Create a Modal Image with system + Python packages."
    return modal.Image.debian_slim().apt_install(apts).pip_install(pips)

# %% ../nbs/01_sandbox.ipynb #0d31800f
def mk_vol(
    name:str # Volume name to look up or create
) -> dict:
    "Look up a Modal Volume by name, creating it if missing."
    return {'/data': modal.Volume.from_name(name, create_if_missing=True)}

# %% ../nbs/01_sandbox.ipynb #f62a2560
import logging

# %% ../nbs/01_sandbox.ipynb #36d84cad
logging.basicConfig(level=logging.INFO, format='%(levelname)s - %(message)s | %(asctime)s')
log = logging.getLogger(__name__)

# %% ../nbs/01_sandbox.ipynb #2c02f113
def mk_sandbox(
    app    :modal.App,    # Modal App to register the Sandbox with
    img    :modal.Image,  # Image for the Sandbox environment
    vol    :dict,         # Volume for the Sandbox environment
    timeout:int,          # auto-terminate after this many seconds
    gpu    :str,          # GPU type (e.g. "T4", "A100") or None
    secrets:dict,         # Sandbox secrets
) -> modal.Sandbox:
    "Create a Modal Sandbox with optional GPU, SSH, and Volumes."
    log.info('∞ creating sandbox; this may take 5-10 minutes if you are creating this sandbox for the first time...')
    sb = modal.Sandbox.create('sleep', 'infinity',  # <1>
        app=app, image=img, volumes=vol,
        unencrypted_ports=[22], 
        timeout=timeout, gpu=gpu,  # <2>
        secrets=[modal.Secret.from_dict(secrets)])
    log.info('✔ sandbox ready')
    return sb

# %% ../nbs/01_sandbox.ipynb #02ca8fce
def get_tunnel(
    sb: modal.Sandbox  # Sandbox with an exposed TCP tunnel
) -> tuple[str,int]:
    "Get unencrypted host and port for a Sandbox's TCP tunnel."
    t = sb.tunnels()[22]
    host, port = t.unencrypted_host, t.unencrypted_port
    log.info(f'✔ gotten tunnel: {host}:{port}')
    return host, port

# %% ../nbs/01_sandbox.ipynb #db3e20e6
import os

# %% ../nbs/01_sandbox.ipynb #76c2029b
def get_pubkey() -> str:
    "SSH public key from environment."
    if 'SSH_PUBKEY' not in os.environ:
        raise KeyError("SSH_PUBKEY not set — cannot connect to sandbox via SSH")
    return os.environ['SSH_PUBKEY']

# %% ../nbs/01_sandbox.ipynb #22acba37
def inject_pubkey(
    sb    :modal.Sandbox,  # Sandbox to inject the key into
    pubkey:str             # SSH public key string
):
    "Inject an SSH public key into the Sandbox's authorized_keys."
    sb.exec('mkdir', '-p', '/root/.ssh')
    sb.exec('bash', '-c', f'echo {pubkey} > /root/.ssh/authorized_keys')
    log.info('✔ public key injected')

# %% ../nbs/01_sandbox.ipynb #7c9fbd91
from time import sleep

# %% ../nbs/01_sandbox.ipynb #a2b3362d
def start_ssh(
    sb: modal.Sandbox  # Sandbox with SSH server installed
):
    "Start SSH service in the Sandbox, waiting up to ~6 seconds for it to come online."
    sb.exec('service', 'ssh', 'start')
    for _ in range(20):
        proc = sb.exec('service', 'ssh', 'status')
        if 'fail' in proc.stdout.read(): sleep(0.3)
        elif 'run' in proc.stdout.read():
            log.info('✔ started ssh service')
            return
    log.error('✖ failed to start ssh service')

# %% ../nbs/01_sandbox.ipynb #1d3817c4
from fastcore.all import *

# %% ../nbs/01_sandbox.ipynb #0e1d5ade
from typing import Callable

# %% ../nbs/01_sandbox.ipynb #310fd93d
def mk_ssh(
    host: str,  # Tunnel host
    port: int,  # Tunnel port
) -> Callable:
    "Return an SSH function for the given Modal tunnel."
    return lambda *cmd: run('ssh', '-p', str(port),
        '-o', 'StrictHostKeyChecking=no',
        '-o', 'UserKnownHostsFile=~/.ssh/known_hosts',
        '-o', 'ConnectTimeout=10',
        f'root@{host}', *cmd)

# %% ../nbs/01_sandbox.ipynb #65fc2209
def verify_ssh(
    ssh: Callable  # SSH function returned by mk_ssh
):
    "Verify SSH connection to Sandbox and print system info."
    h, u, w = ssh('hostname; uname -srmo; whoami').splitlines()[:3]
    sys_name, ver, arch, os_name = u.split()
    gpu = ssh('nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null || echo "no GPU"').strip()
    print(f'System: {sys_name}')
    print(f'Hostname: {h}')
    print(f'User: {w}')
    print(f'Kernel: {ver}')
    print(f'Architecture: {arch}')
    print(f'OS Type: {os_name}')
    print(f'GPU: {gpu}')

# %% ../nbs/01_sandbox.ipynb #7bda2361
def get_apts() -> list[str]:
    "List installed system package names."
    return run('dpkg-query -W -f=\'${Package}\\n\'').splitlines()

# %% ../nbs/01_sandbox.ipynb #f0a23ee7
def get_pips() -> list[str]:
    "List installed Python packages (name==version)."
    return [l for l in run('pip freeze').splitlines() if not l.startswith(('-e', '@'))]

# %% ../nbs/01_sandbox.ipynb #60d610ef
import socket, os

# %% ../nbs/01_sandbox.ipynb #e83fa224
def in_modal() -> str: 
    'Checks whether current environment is Modal or not.'
    return socket.gethostname() == 'modal'

# %% ../nbs/01_sandbox.ipynb #9fe893b8
def in_solveit(): 
    'Checks whether current environment is SolveIt or not.'
    return bool(os.environ.get('IN_SOLVEIT'))
